version: '3'
services:
  postgres:
    image: postgres
    hostname: localhost
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: di_bot
      POSTGRES_PASSWORD: dipadissdiwd
      POSTGRES_DB: di_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

#  pgadmin:
#    image: dpage/pgadmin4
#    depends_on:
#      - postgres
#    ports:
#      - 5555:80
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: diadmin
#    restart: unless-stopped

volumes:
  postgres-data: