version: '3'
services:
  postgres:
    image: postgres
    hostname: localhost
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: di_bot
      POSTGRES_PASSWORD: dipadissdiwd
      POSTGRES_DB: di_bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  di_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5555:5555
    restart: unless-stopped
    command: python main.py
    depends_on:
      - postgres


volumes:
  postgres-data: